DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Account;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE Orders (
    id UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
    exchange_order_id VARCHAR(255)
);

CREATE TABLE Account (
    id VARCHAR PRIMARY KEY
);